MOBILE-358: Extensible Navbar Buttons
bounswe/bounswe2024group6 pull request #359
Opened 2024-10-20 15:15 UTC by YavizGuldalf

This PR includes a small functional change to the Navbar component. It can be used in the same way as before, but now it also takes 4 optional arguments for the 4 buttons it has to enable extending its functionality. These optional functions are called before the Navbar performs its normal onPress functionality.

2024-10-20 17:47 UTC, aoengin commented
> These optional functions are called before the Navbar performs its normal onPress functionality.

I requested this change because I only want the page to scroll up if the user taps the quizzes section while already in the quizzes section. I don't want any routing to occur if the user is already on the quiz feed page. However, it will still route if the optional functions don't override the default functionality.

2024-10-20 17:48 UTC, aoengin requested changes
> These optional functions are called before the Navbar performs its normal onPress functionality.

I requested this change because I only want the page to scroll up if the user taps the quizzes section while already in the quizzes section. I don't want any routing to occur if the user is already on the quiz feed page. However, it will still route if the optional functions don't override the default functionality.

2024-10-20 18:10 UTC, YavizGuldalf commented
Given that the Navbar component uses the function `router.navigate` when the buttons are pressed, I don't think that will be an issue. That function only routes to a new screen if it's different from the one it's already in. Here's the related section from Expo documentation (you can find more at https://docs.expo.dev/router/navigating-pages/#imperative-navigation):

<img width="776" alt="Screenshot 2024-10-20 at 21 03 51" src="https://github.com/user-attachments/assets/105a8e96-83bf-4e2e-b32e-83ca0f449ced">

Nonetheless, I added the option you requested under the prop name homeOnPressOverride, quizOnPressOverride etc. Let me know if there are any other problems.

2024-10-21 17:35 UTC, aoengin commented
LGTM!

2024-10-21 17:35 UTC, merged